### PR TITLE
Closes #210 - Fix bug in calculating rating

### LINKED ISSUE #210: Fix bug in calculating total rating
https://jira.softserve.academy/browse/CDXCII-93

### PR DESCRIPTION
**Pull request by romadmn**

### CODE REVIEW

**Review by MaksymNovitskyi — APPROVED** [review]

**Review by Digicat13 — APPROVED** [review]

File: src/app/shared/components/comment/comment.component.ts [hunk 1]
```diff
@@ -104,7 +104,6 @@ export class CommentComponent implements OnInit {
   }
 
   updateComments() {
-    console.log("dadada")
```
Comment (VitaliyRud2001) [inline src/app/shared/components/comment/comment.component.ts:107]: dadada

**Review by VitaliyRud2001 — APPROVED** [review]
